### ISSUE TITLE
Use files section instead of field for image source 

### ISSUE THREAD

**Issue by eighthday** [sylvainjule/kirby-annotator#10]
Is it possible for the annotator src to automatically pick the first image in a files section ? 

At the moment I have two fields - one to upload one to select - is this right?

<img width="953" alt="Screenshot 2019-04-12 at 16 00 42" src="https://user-images.githubusercontent.com/4104767/56046998-6bd43100-5d3c-11e9-929f-217679a6dfaa.png">

another wonderful plugin btw !

**Comment by sylvainjule** [comment]
I would tend to consider this solved by the ability to upload an image directly within the Files field, wouldn't you?
It's much clearer this way than with a section, in my opinion.
