### ISSUE TITLE
Cannot read property 'current' of undefined in the Panel

### ISSUE THREAD

**Issue by georgobermayr** [sylvainjule/kirby-annotator#11]
Hi,

I have an "Cannot read property 'current' of undefined" exception in the Panel when using the Annotator field. I think this was introduced in Kirby 3.3.0 and could be, from what I read, related to the refactoring of the Vuex form store module?

Thank you,
Georg

**Comment by lukehatfield** [comment]
I'm seeing this with Kirby 3.6.1.1 and Annotator version 0.0.1.

![image](https://user-images.githubusercontent.com/5399943/149359614-07afa632-8cea-4be0-ae3c-a39efadf0ba1.png)

**Comment by sylvainjule** [comment]
I've just released 1.0.5, which you'll need for 3.6+ compatibility.
