### ISSUE TITLE
Percentages decimal points in French

### ISSUE THREAD

**Issue by cadars** [sylvainjule/kirby-annotator#13]
When having french as a site language, decimal points for the markers values get converted to commas (and then aren't valid CSS). I was able to circumvent this with a simple str_replace:
`<?php echo str_replace(',', '.', markerStyle($marker)) ?>` but thought you'd like to know.

**Comment by sylvainjule** [comment]
This is a LC_NUMERIC issue. Can you try setting your locale to `fr_FR.utf-8`? This should fix it.

```php "/site/config/config.php
return [
  'locale' => 'fr_FR.utf-8'
];
```

**Comment by sylvainjule** [comment]
Should be fixed by 268f1fa. Please reopen if needed!
