### ISSUE TITLE
Changing color with complete example results in JS Error

### ISSUE THREAD

**Issue by oliverschneider** [sylvainjule/kirby-annotator#15]
`undefined is not an object (evaluating 'this.$annotator.updateFields')`

This is what I get if I want to change the color when using the complete example from the docs in the latest Kirby Version.

**Comment by Werbschaft** [comment]
<img width="1291" alt="Bildschirmfoto 2020-10-16 um 14 55 51" src="https://user-images.githubusercontent.com/2178466/96260850-e203c480-0fbf-11eb-9a3e-6c6a81e2a9ef.png">

For me the same here ...
