### ISSUE TITLE
Bug with Positions

### ISSUE THREAD

**Issue by Werbschaft** [sylvainjule/kirby-annotator#16]
<img width="1292" alt="Bildschirmfoto 2020-10-16 um 14 56 01" src="https://user-images.githubusercontent.com/2178466/96261895-512de880-0fc1-11eb-9fb5-4d994cec25e1.png">

On Refresh, all markers get on the left top. There's no way to get them back to the right Position. Also no resize or similar. Setup is done in the file blueprint as I want to use it with the builder field and there aren't sections possible.

Edit: I have found a solution, the values aren't saved in the structure field with a point, they are saved with a comma. Changing the fields to number format does the trick. In config.php we have set the correct local but without any changes.

Seems like this is similar to this: https://github.com/sylvainjule/kirby-annotator/issues/13

I created a pull request, hope it's ok. I don't have many experience with github ...

**Comment by sylvainjule** [comment]
Thank you! I have merged the PR!
