### ISSUE TITLE
this.load is not a function in Kirby 3.6.1

### ISSUE THREAD

**Issue by RobertCordes** [sylvainjule/kirby-annotator#21]
After updating to Kirby 3.6.1 I got the following error, when visiting the panel with an annotator field:

> this.$store.state.languages ? this.$store.state.languages.current : this.$language

This is referring to [this line](https://github.com/sylvainjule/kirby-annotator/blob/092339c6c3e555322a61bf77495a1aa757a5c412/src/annotator.vue#L127) in **src/annotator.vue**.

Switching back to 3.6.0 I got rid of the error. Unfortunately I have no idea what `this.load()` is for, otherwise I would happily create a PR. 😉

**Comment by sylvainjule** [comment]
Thanks for reporting this, not much we could do currently as it's a regression in 3.6.1, you'd have to stick to 3.6.0 for now. An issue is open here: https://github.com/getkirby/kirby/issues/1062
