### ISSUE TITLE
4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [sylvainjule/kirby-annotator#23]
Tested on 4.0.0-beta.1 and the plugin doesn't working correctly. Tools on image are can't be clicked.

![screen-capture-1611-Test - Mægazine-localhost](https://github.com/sylvainjule/kirby-annotator/assets/3393422/2eb92470-f388-4795-8bfe-aad859855b80)

**Comment by squareclouds** [comment]
would be great to have this plugin ready soon! :) it was always very helpful

**Comment by distantnative** [comment]
@sylvainjule the computed `disabled` prop should probably read now

```js
return !this.translate && !this.$panel.language.default
```

**Comment by sylvainjule** [comment]
This plugin should now work in K4 ✓
