### ISSUE TITLE
Min/Max annotation

### ISSUE THREAD

**Issue by findthebug** [sylvainjule/kirby-annotator#6]
it would be great if it were possible to limit the number of annotations. In my case, I only need 1 annotation and want to prevent multiple annotations from being added. Unfortunately I can't set this with "min" or "max". When I click on the image, unlimited annotation is added, even i add min or max to the structure fields in the marker section.

**Comment by sylvainjule** [comment]
I've added a `max` option. ✅ 
The `min` option of the structure field itself will work fine.

[Documented it here](https://github.com/sylvainjule/kirby-annotator#min--max)
