### ISSUE TITLE
Zoom function for large images

### ISSUE THREAD

**Issue by findthebug** [sylvainjule/kirby-annotator#7]
It would be cool if there would be an image zoom function. with this you could zoom in/out on the image and set the markers even more precisely.

**Comment by sylvainjule** [comment]
I've added a `zoom: true | false` option:

![Screen Recording 2019-03-19 at 12 27 AM](https://user-images.githubusercontent.com/14079751/54570339-7c63e680-49de-11e9-8650-a91ef0061dc0.gif)

Note that it's desktop-only.
