### ISSUE TITLE
'The section type "annotator" is not valid' on remote server

### ISSUE THREAD

**Issue by samvantoever** [sylvainjule/kirby-annotator#8]
Are there any undocumented server requirements for Annotator to work? The plugin works perfect locally, but gives a `The section type "annotator" is not valid` error in the panel on the remote server.

**Comment by sylvainjule** [comment]
Sorry for the delay.
Well, not at all, no. Do you still have the issue? 

Have you, by any chance, updated an existing remote server install by adding of the annotator plugin afterwards? If so, I would try to delete what's in the `media/plugins` folder to make sure you're not dealing with an old `index.js`.

**Comment by samvantoever** [comment]
Thanks for the reply, that fixed it! Had no clue that file could get outdated.
